version: "3"
services:
  server:
    container_name: mangrove-server
    build: .
    ports:
      - '8000:8000'
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=edward
    #   - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-db:/data/db # named volume - name:path

# need to do this for named volumes since can be used across multiple services
volumes:
  mongo-db: 