version: "3.4"

services:
  server:
    container_name: mangrove-server
    build: 
      context: .
      target: development
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '8000:8000'
    command: npm run dev
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-db:/data/db # named volume - name:path

# need to do this for named volumes since can be used across multiple services
volumes:
  mongo-db: 